
version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging into Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 766037821005.dkr.ecr.ap-south-1.amazonaws.com
      - aws ecr get-login-password --region ap-northeast-3 | docker login --username AWS --password-stdin 766037821005.dkr.ecr.ap-northeast-3.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t dc-web-app:latest .
      - docker tag dc-web-app:latest 766037821005.dkr.ecr.ap-south-1.amazonaws.com/dc-web-app:latest
      - docker tag dr-web-app:latest 766037821005.dkr.ecr.ap-northeast-3.amazonaws.com/dr-web-app:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images to ECR...
      - docker push 766037821005.dkr.ecr.ap-south-1.amazonaws.com/dc-web-app:latest
      - docker push 766037821005.dkr.ecr.ap-northeast-3.amazonaws.com/dr-web-app:latest
      - echo Writing image definitions...
      - printf '[{"name":"dc-web-App","imageUri":"%s"}]' 766037821005.dkr.ecr.ap-south-1.amazonaws.com/dc-web-app:latest > imagedef_primary.json
      - printf '[{"name":"dr-web-App","imageUri":"%s"}]' 766037821005.dkr.ecr.ap-northeast-3.amazonaws.com/dr-web-app:latest > imagedef_secondary.json
artifacts:
  files:
    - imagedef_primary.json
    - imagedef_secondary.json
